name: Build and deploy Web App and Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # TRABALHO 1: Implantar o site (Frontend "Loja")
  deploy-webapp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vision-az-linux'
          package: ./frontend

  # TRABALHO 2: Implantar a função de processamento (Backend "Fábrica")
  deploy-functionapp:
    runs-on: ubuntu-latest
    needs: deploy-webapp
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      # PASSO CRÍTICO ADICIONADO: Build explícito com Oryx
      - name: Build Function App with Oryx
        uses: Azure/oryx-action@v1
        with:
          platform: python
          platform-version: '3.11'
          app-dir: './function_app'
          publish-output: './oryx_build_output'

      # PASSO ATUALIZADO: Usa o output do Oryx
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'vision-az-functions-ian'
          package: './oryx_build_output'

      # PASSO ADICIONADO: Sincronização manual de triggers
      - name: Sync triggers and restart
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp restart --name vision-az-functions-ian --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
            az functionapp sync --name vision-az-functions-ian --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
            sleep 30  # Aguarda a inicialização