name: Build and deploy Web App and Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # TRABALHO 1: Implantar o site (Frontend) - Mantido inalterado
  deploy-webapp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vision-az-linux'
          package: ./frontend

  # TRABALHO 2: Implantar a função de processamento (Backend) - ATUALIZADO para nova estrutura
  deploy-functionapp:
    runs-on: ubuntu-latest
    needs: deploy-webapp
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # PASSO ATUALIZADO: Instala dependências no novo diretório backend/functions
      - name: Install Python dependencies for Function App
        run: |
          cd backend/functions
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"
          
          # Instala dependências adicionais para processamento
          pip install opencv-python-headless PyMuPDF Pillow

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      # PASSO ATUALIZADO: Deploy apontando para o novo diretório backend/functions
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'vision-az-functions-ian'
          package: ./backend/functions
          # Habilitar build Oryx para dependências nativas
          enable-oryx-build: true
          
      # PASSO ADICIONAL: Configurar PYTHONPATH para acesso aos módulos compartilhados
      - name: Configure Python Path
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE/backend/shared" >> $GITHUB_ENV
        shell: bash