# Arquivo: .github/workflows/main_vision-az-linux.yml
# Versão final e completa, desenhada para a estrutura refatorada.
# Este workflow implanta tanto o site (App Service) quanto a função (Function App).

name: Build and deploy Web App and Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # TRABALHO 1: Implantar o site (Frontend "Loja")
  deploy-webapp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vision-az-linux'
          # Aponta para a pasta correta do frontend.
          # O sistema de build do Azure (Oryx) irá detetar o
          # requirements.txt e instalar as dependências.
          package: ./frontend

  # TRABALHO 2: Implantar a função de processamento (Backend "Fábrica")
  deploy-functionapp:
    runs-on: ubuntu-latest
    # Garante que a função só será implantada se o deploy do site for bem-sucedido
    needs: deploy-webapp
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instala as dependências (Pillow, moviepy, etc.) na estrutura correta
      # para ser empacotada e enviada para o Azure.
      - name: Install Python dependencies for Function App
        run: |
          python -m pip install --upgrade pip
          pip install -r ./function_app/requirements.txt --target="./function_app/.python_packages/lib/python3.11/site-packages"

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          # Usa os mesmos segredos que já estão configurados
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A49747CD89F4688882C8FF9592511B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20782B1DE23448ACBECB0F8807D5B218 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F558C0E4056849249AA4CE88EDC41690 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          # Garanta que este é o nome exato do seu Aplicativo de Funções
          app-name: 'vision-az-functions-ian' 
          # Aponta para a pasta do backend, que agora contém o código e as dependências
          package: ./function_app
